# Application replicas
replicaCount: 1

# Docker image info
image:
  repository: "pinkmelon/resource-service"
  tag: 27

# Service config
service:
  type: LoadBalancer
  port: 8081

# Deployment history
revisionHistoryLimit: 3
