# Application replicas
replicaCount: 1

# Docker image info
image:
  repository: "pinkmelon/resource-service"
  tag: 36

# Service config
service:
  type: NodePort
  port: 8081

# Deployment history
revisionHistoryLimit: 3
